### ISSUE TITLE
Failed to export to different file formats

### ISSUE THREAD

**Issue by SergeyMi37** [heloisatambara/iris-size-django#1]
Failed to export to different file formats

**Comment by heloisatambara** [comment]
Hi Sergey! Would you please describe the problem a little more? I couldn't find the same issue to correct it.
The files will be exported to the iris-size-django directory as shown in the following image:
![image](https://github.com/heloisatambara/iris-size-django/assets/81993336/c61e7ebe-3b72-4bd1-9124-ce27d3b9fa78)

Is it possible that you searched on a different path? If not, please tell me so I can keep looking for a solution!

**Comment by SergeyMi37** [comment]
Hi Heloisa.
Exactly! I was looking for files in the wrong place.
